<?php
/**
 * @file
 * Twitter Auth Api for drupal.
 */

/**
 * Implements hook_libraries_info().
 */
function idevels_twitter_login_libraries_info() {
  $libraries['twitteroauth'] = array(
    'name' => 'Twitter OAuth Library',
    'vendor url' => 'https://twitteroauth.com/',
    'download url' => 'https://github.com/abraham/twitteroauth',
    'version' => 'git',
    'files' => array(
      'php' => array(
        'autoload.php',
      ),
    ),
  );
  return $libraries;
}
