- name: "Restart Exim4"
  service: 
    name: exim4
    tate: restarted 
    enabled: yes

- name: "Reload Exim4"
  service: 
    name: exim4
    tate: reloaded 
    enabled: yes

- name: "Restart New Relic"
  service:
    name: newrelic-sysmond
    state: restarted

- name: "Reload New Relic"
  service:
    name: newrelic-sysmond
    state: reloaded

- name: "Restart New Relic Daemon"
  service:
    name: newrelic-daemon
    state: restarted

- name: "Reload New Relic Daemon"
  service:
    name: newrelic-daemon
    state: reloaded

- name: "Restart PHP-FPM"
  service:
    name: php5-fpm
    state: restarted

- name: "Reload PHP-FPM"
  service:
    name: php5-fpm
    state: reloaded

- name: "Restart Nginx"
  service:
    name: nginx
    state: restarted

- name: "Reload Nginx"
  service:
    name: nginx
    state: reloaded

- name: "Restart Ssh"
  service:
    name: ssh
    state: restarted

- name: "Reload Ssh"
  service:
    name: ssh
    state: reloaded

- name: "Restart Fail2ban"
  service:
    name: fail2ban
    state: restarted

- name: "Reload Fail2ban"
  service:
    name: fail2ban
    state: reloaded

- name: "Restart Zabbix Agent"
  service:
    name: zabbix-agent
    state: restarted

- name: "Reload Zabbix Agent"
  service:
    name: zabbix-agent
    state: reloaded

- name: "Restart Varnish"
  service: 
    name: varnish 
    state: restarted

- name: "Reload Varnish"
  service: 
    name: varnish 
    state: reloaded

- name: "Restart Memcached"
  service: 
    name: memcached
    state: restarted

- name: "Reload Memcached"
  service: 
    name: memcached
    state: reloaded

- name: "Restart Mysql"
  service: 
    name: mysql
    state: restarted

- name: "Reload Mysql"
  service: 
    name: mysql
    state: reloaded
