- name: "Install Composer into the current directory."
  shell: >
    curl -sS https://getcomposer.org/installer | php
    creates={{ composer_path }}

- name: "Move Composer into globally-accessible location."
  shell: >
    mv composer.phar {{ composer_path }}
    creates={{ composer_path }}

- name: "Clone Drush from GitHub."
  git:
    repo=https://github.com/drush-ops/drush.git
    dest={{ drush_install_path }}
    version={{ drush_version }}

- name: "Install Drush dependencies with Composer."
  shell: >
    {{ composer_path }} install --prefer-source --no-interaction
    chdir={{ drush_install_path }}
    creates={{ drush_install_path }}/vendor/autoload.php

- name: "Create drush symlink."
  file: >
    src={{ drush_install_path }}/drush
    dest={{ drush_path }}
    state=link

- name: "Run drush to finish setting it up."
  command: "{{ drush_path }}"
  register: drush_result
  changed_when: "'Execute a drush command' not in drush_result.stdout"

