  - name: "Install Mailcatcher dependency"
    apt:
      pkg: "{{ item }}"
      update_cache: true
    with_items:
      - sqlite3
      - libsqlite3-dev
      - rubygems
      - ruby-dev
      - ssmtp

  - name: "Install Mailcatcher"
    command: gem install mailcatcher

  - name: "Create startup script for mailcatcher"
    template: src=templates/mailcatcher.j2 dest=/etc/init.d/mailcatcher mode=0755

  - name: "Mailcatcher will start upon boot"
    command: update-rc.d mailcatcher defaults

  - name: "Make sure Mailcatcher is not running"
    command: pkill mailcatcher
    ignore_errors: yes

  - name: "Start Mailcatcher properly with the start script"
    command: /etc/init.d/mailcatcher

  - name: "Copy ssmtp config file."
    template:
      src=templates/ssmtp.conf.j2
      dest=/etc/ssmtp/ssmtp.conf
      owner=root group=root mode=644