- name: "Add dotdeb key"
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- name: "Add apt dotdeb repo"
  apt_repository: repo='deb http://packages.dotdeb.org {{ ansible_distribution_release }} all' state=present
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- name: "Add apt dotdeb php 5.5 repo"
  apt_repository: repo='deb http://packages.dotdeb.org wheezy-php55 all' state=present
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- name: "Install php"
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ] 
  apt:
    pkg: "{{ item }}"
    update_cache: true
    state: latest
  with_items:
    - php5-fpm
    - php5-cli
    - php5-mysql
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-imap
    - php5-mcrypt
    - php5-pspell 
    - php5-recode 
    - php5-snmp 
    - php5-tidy 
    - php5-xmlrpc 
    - php5-xsl


