- name: "Create drupal database"
  mysql_db: name={{ mysql_drupal_database }} state=present

- name: "Set user privileges"
  mysql_user:
    user={{ mysql_drupal_user }}
    password={{ mysql_drupal_password }}
    state=present
    priv={{ item }}
  with_items:
    - '{{  mysql_drupal_database }}.*:ALL'

- name: "deploy drupal database"
  mysql_db: name={{ mysql_drupal_database }} state=import target=/var/www/db.sql

- name: "Creates nginx vhosts directory"
  file: path=/etc/nginx/sites-enabled/ state=directory

- name: "Copy nginx vhost configuration in place."
  template:
    src=templates/etc/nginx/sites-enabled/drupal.conf.j2
    dest=/etc/nginx/sites-enabled/drupal.conf
    owner=root group=root mode=644

- name: "Ensure nginx is started and enabled to start at boot."
  service: name=nginx state=restarted enabled=yes

- name: "Create settings.php file"
  command: touch /var/www/sites/default/settings.php
  ignore_errors: yes

- name: "Deploy settings.php file"
  template:
    src=templates/drupal/sites/default/settings.php.j2
    dest=/var/www/sites/default/settings.php

- name: "Create services.yml file"
  command: touch /var/www/sites/default/services.yml
  ignore_errors: yes

- name: "Deploy services.yml file"
  template:
    src=templates/drupal/sites/default/services.yml.j2
    dest=/var/www/sites/default/services.yml

- name: "Execute drush commands and fix file permissions"
  shell: "{{ item }} chdir=/var/www/htdocs/"
  with_items:
    # link sites directory (drupal as submodule)
    - ln -fs /var/www/sites/ /var/www/htdocs/
    - ln -fs /var/www/modules/ /var/www/htdocs/
    # clear drupal cache
    - drush cache-rebuild
    # fix file permissions
    - chmod -R 777 sites/default/files/
