- name: "Install system utils"
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
  apt:
    pkg: "{{ item }}"
    update_cache: true
  with_items:
    - htop
    - mc
    - rcconf
    - ncdu
    - pwgen
    - curl
    - p7zip-full
    - screen
    - imagemagick
    - git
    - tig
    - apt-transport-https
    - python-pycurl
    - lsb-release
    - apt-transport-https
    #- build-essential
    #- openssl
    #- libssl-dev
    #- sqlite3
    #- libsqlite3-dev
    #- rubygems
    #- ruby-dev
    #- ssmtp


