- name: Add official APT repository
  when: ansible_os_family == 'Debian'
  sudo: yes
  register: _repo
  apt_repository:
    repo: 'deb http://repo.varnish-cache.org/{{ansible_distribution|lower()}}/ {{ ansible_distribution_release }} varnish-{{varnish_version}}'
  tags:
    - repo
    - varnish
    - http-cache

- name: Retrieve repo signing key
  when: ansible_os_family == 'Debian'
  sudo: yes
  register: _repo_key
  apt_key:
    url: "http://repo.varnish-cache.org/{{ansible_distribution|lower()}}/GPG-key.txt"
  tags:
    - repo
    - varnish
    - http-cache

- name: Update repository caches
  when: ansible_os_family == 'Debian' and (_repo_key.changed or _repo.changed)
  sudo: yes
  apt: update_cache=yes
  tags:
    - repo
    - varnish
    - http-cache

- name: Install Varnish
  when: ansible_os_family == 'Debian'
  sudo: yes
  apt: name=varnish state=present
  tags:
    - deps
    - varnish
    - http-cache

- name: Create configuration directories
  file:
    dest: "{{item}}"
    state: directory
  with_items:
    - "{{varnish_vcl_dir}}"
  tags:
    - conf
    - varnish
    - http-cache

- name: Configure Varnish
  sudo: yes
  template:
    src: templates/etc/default/varnish.conf.j2
    dest: "{{varnish_conf_file}}"
  notify: Restart Varnish
  tags:
    - conf
    - varnish
    - http-cache

- name: "VCL Create"
  sudo: yes
  template:
    src: templates/etc/varnish/default.vcl.j2
    dest: /etc/varnish/default.vcl
  when: state is not defined or state == 'present'
  notify: Reload Varnish
  tags:
    - conf
    - vcl
    - varnish
    - http-cache
