- name: "Install xhprof extension"
  apt:
    pkg: "{{ item }}"
    update_cache: true
  with_items:
    - php5-xhprof

- name: "Configure xhprof extension."
  template:
    src="templates/20-xhprof.ini.j2"
    dest="/etc/php5/conf.d/20-xhprof.ini"
    owner="root" group="root" mode="644"

- name: "Clone xhprof from GitHub."
  git:
    repo=http://git.internetdevels.com/mula/xhprof.git
    dest={{ xhprof_install_path }}
    version={{ xhprof_version }}

- name: "Copy xhprof configuration in place."
  template:
    src="templates/xhprof.inc.j2"
    dest="/var/www/xhprof/xhprof.inc"
    owner={{ nginx_user }} group={{ nginx_user }} mode="644"

- name: "Creates xhprof log directory"
  file: path=/var/www/xhprof/xhprof_log state=directory