---
# This playbook installs vim and probably packages which some devs may want to have

- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  sudo: yes

  tasks:
    - name: "Install Vi Improved"
      apt: name=vim state=present
