# Ansible playbook for a Drupal idevels server.
#
# If this is being used within a Vagrant profile, you can update your server
# by running `vagrant provision` again.
#
# @author mula (2014).
#

- hosts: drupalua
  gather_facts: yes
  sudo: true

  vars_files:
    - vars/main.yml

  tasks:
  # base tasks for drupal enviroment
  - include: tasks/locale.yml
  - include: tasks/sysutils.yml
  - include: tasks/nginx.yml
  - include: tasks/percona.yml
  - include: tasks/fpm.yml
  - include: tasks/php.yml
  - include: tasks/drush.yml
  - include: tasks/xhprof.yml
  - include: tasks/phpmyadmin.yml
  - include: tasks/varnish.yml
  - include: tasks/osupgrade.yml
  - include: tasks/project.yml

  handlers:
    - include: handlers/main.yml



